// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.InvokeModelResponse;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeClient;

public class InvokeModel extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region Region;
	private IMendixObject __InvokeModelRequest;
	private amazonbedrockconnector.proxies.InvokeModelRequest InvokeModelRequest;

	public InvokeModel(IContext context, IMendixObject Credentials, java.lang.String Region, IMendixObject InvokeModelRequest)
	{
		super(context);
		this.__Credentials = Credentials;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
		this.__InvokeModelRequest = InvokeModelRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.InvokeModelRequest = this.__InvokeModelRequest == null ? null : amazonbedrockconnector.proxies.InvokeModelRequest.initialize(getContext(), __InvokeModelRequest);

		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(InvokeModelRequest, "InvokeModelGenericRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			validateRequest();
			
			BedrockRuntimeClient client = AmazonBedrockClient.getBedrockRuntimeClient(Credentials, Region, InvokeModelRequest);
			
			software.amazon.awssdk.services.bedrockruntime.model.InvokeModelRequest awsRequest = getAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrockruntime.model.InvokeModelResponse awsResponse = client.invokeModel(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			InvokeModelResponse mxResponse = getMxResponse(awsResponse);
			
			return mxResponse.getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InvokeModel";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(InvokeModel.class);
	
	private void validateRequest() {
		if (InvokeModelRequest.getModelID() == null|| InvokeModelRequest.getModelID().isBlank()) {
			throw new IllegalArgumentException("ModelId is required. Please provide the model id of the model you want to invoke.");
		}
		
		if (InvokeModelRequest.getRequestBody() == null || InvokeModelRequest.getRequestBody().isBlank()) {
			throw new IllegalArgumentException("RequestBody is required. Please provide a valid request body of the model you want to invoke.");
		}
	}
	
	private software.amazon.awssdk.services.bedrockruntime.model.InvokeModelRequest getAwsRequest() {
		return software.amazon.awssdk.services.bedrockruntime.model.InvokeModelRequest.builder()
		.body(software.amazon.awssdk.core.SdkBytes.fromUtf8String(InvokeModelRequest.getRequestBody()))
		.modelId(InvokeModelRequest.getModelID())
		.build();
	}
	
	private InvokeModelResponse getMxResponse(software.amazon.awssdk.services.bedrockruntime.model.InvokeModelResponse awsResponse) {
		var mxResponse = new InvokeModelResponse(getContext());
		
		mxResponse.setResponseBody(awsResponse.body().asUtf8String());
		
		return mxResponse;
	}
	
	// END EXTRA CODE
}
