// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.Map;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import amazonbedrockconnector.impl.MxLogger;

public class JA_CohereEmbed_ModifyJson_Response extends CustomJavaAction<java.lang.String>
{
	private java.lang.String ResponseBody_ToBeModified;

	public JA_CohereEmbed_ModifyJson_Response(IContext context, java.lang.String ResponseBody_ToBeModified)
	{
		super(context);
		this.ResponseBody_ToBeModified = ResponseBody_ToBeModified;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Import necessary packages


		try {
			requireNonNull(this.ResponseBody_ToBeModified, "ResponseBody String is required");
        // Initialize ObjectMapper with full response body as received from Cohere Embed
			ObjectNode root = (ObjectNode) mapper.readTree(ResponseBody_ToBeModified);
			ObjectNode outputNode = null;
			
			
			if (isRootEmpty(root)) {
				LOGGER.warn("Root node is empty or does not contain required fields.");
				return null;
			} {
				
				// Parse the input JSON
				JsonNode inputNode = mapper.readTree(this.ResponseBody_ToBeModified);

				// Create output JSON object
				outputNode = mapper.createObjectNode();
				outputNode.set("id", inputNode.get("id"));
				outputNode.set("response_type", inputNode.get("response_type"));

				// Create the embeddings array for the output
				ArrayNode outputEmbeddingsArray = mapper.createArrayNode();

				// Get input embeddings and texts arrays
				JsonNode embeddingsNode = root.get("embeddings");


            // Check if embeddingsNode is an array or an object
            if (embeddingsNode.isArray()) {
                // Handle case where embeddings is an array
                ArrayNode inputEmbeddingsArray = (ArrayNode) embeddingsNode;
                for (JsonNode embeddingArray : inputEmbeddingsArray) {
                    try {
                        String embeddingString = (embeddingArray != null ? mapper.writeValueAsString(embeddingArray) : "");
                        ObjectNode embeddingObject = mapper.createObjectNode();
                        embeddingObject.put("vector", embeddingString);
                        embeddingObject.put("_index", outputEmbeddingsArray.size());
                        outputEmbeddingsArray.add(embeddingObject);
                    } catch (Exception e) {
                        LOGGER.error("Error processing embedding array: " + e.getMessage());
                        throw e;
                    }
                }
            } else if (embeddingsNode.isObject()) {
                // Handle case where embeddings is an object with nested arrays
                ObjectNode embeddingsObject = (ObjectNode) embeddingsNode;
                embeddingsObject.fields().forEachRemaining(entry -> {
                    ArrayNode inputEmbeddingsArray = (ArrayNode) entry.getValue();
                    for (JsonNode embeddingArray : inputEmbeddingsArray) {
                        try {
                            String embeddingString = (embeddingArray != null ? mapper.writeValueAsString(embeddingArray) : "");
                            ObjectNode embeddingObject = mapper.createObjectNode();
                            embeddingObject.put("vector", embeddingString);
                            embeddingObject.put("_index", outputEmbeddingsArray.size());
                            outputEmbeddingsArray.add(embeddingObject);
                        } catch (Exception e) {
                            LOGGER.error("Error processing embedding array: " + e.getMessage());
                            throw new RuntimeException(e);
                        }
                    }
                });
            }




            // Add embeddings array to output
            outputNode.set("embeddings", outputEmbeddingsArray);

			}

				return mapper.writeValueAsString(outputNode);

				// Convert outputNode to String and return

			} catch (Exception e) {
				LOGGER.error("Error occurred while modifying Cohere Embed response body: " + e.getMessage());
				throw e;
			}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CohereEmbed_ModifyJson_Response";
	}

	// BEGIN EXTRA CODE

	private static final MxLogger LOGGER = new MxLogger(JA_CohereEmbed_ModifyJson_Response.class);
	private static final ObjectMapper mapper = new ObjectMapper();

	private boolean isRootEmpty(ObjectNode root) {
        return root == null || !root.hasNonNull("id") || !root.hasNonNull("response_type") ||
               !root.hasNonNull("embeddings") ||
               ((root.get("embeddings").isArray() && ((ArrayNode) root.get("embeddings")).size() == 0) ||
                (root.get("embeddings").isObject() && root.get("embeddings").size() == 0));
    }

	// END EXTRA CODE
}
