// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.MxLogger;
import system.proxies.Image;

public class JA_ResponseImage_CreateSpecialization extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ResponseImage;
	private system.proxies.Image ResponseImage;

	public JA_ResponseImage_CreateSpecialization(IContext context, IMendixObject ResponseImage)
	{
		super(context);
		this.__ResponseImage = ResponseImage;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.ResponseImage = this.__ResponseImage == null ? null : system.proxies.Image.initialize(getContext(), __ResponseImage);

		// BEGIN USER CODE
		try {
			
			IMendixObject responseImage = Core.instantiate(getContext(), this.ResponseImage.getMendixObject().getId().getObjectType());
			
			return responseImage;
			
		} catch (Exception e) {
			LOGGER.error("Error ocurred while creating response image object: " + e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ResponseImage_CreateSpecialization";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(JA_ResponseImage_CreateSpecialization.class);
	// END EXTRA CODE
}
