// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.ENUM_CustomizationType;
import amazonbedrockconnector.proxies.ENUM_InferenceType;
import amazonbedrockconnector.proxies.ENUM_InputOutputModality;
import amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus;
import amazonbedrockconnector.proxies.FoundationModelLifecycle;
import amazonbedrockconnector.proxies.FoundationModelSummary;
import amazonbedrockconnector.proxies.InputModality;
import amazonbedrockconnector.proxies.ListFoundationModelsResponse;
import amazonbedrockconnector.proxies.OutputModality;
import amazonbedrockconnector.proxies.SupportedCustomization;
import amazonbedrockconnector.proxies.SupportedInferenceType;
import software.amazon.awssdk.services.bedrock.BedrockClient;

public class ListFoundationModels extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region Region;
	private IMendixObject __ListFoundationModelsRequest;
	private amazonbedrockconnector.proxies.ListFoundationModelsRequest ListFoundationModelsRequest;

	public ListFoundationModels(IContext context, IMendixObject Credentials, java.lang.String Region, IMendixObject ListFoundationModelsRequest)
	{
		super(context);
		this.__Credentials = Credentials;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
		this.__ListFoundationModelsRequest = ListFoundationModelsRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.ListFoundationModelsRequest = this.__ListFoundationModelsRequest == null ? null : amazonbedrockconnector.proxies.ListFoundationModelsRequest.initialize(getContext(), __ListFoundationModelsRequest);

		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(ListFoundationModelsRequest, "ListFoundationalModelsRequest is required");
			requireNonNull(Region, "AWS Region is required");
						
			BedrockClient client = AmazonBedrockClient.getBedrockClient(Credentials, Region, ListFoundationModelsRequest);
			
			software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest awsRequest = createAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrock.model.ListFoundationModelsResponse awsResponse = client.listFoundationModels(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return getMxResponse(awsResponse).getMendixObject();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListFoundationModels";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ListFoundationModels.class);
	
	private software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest createAwsRequest(){
		
		software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest.Builder awsRequestBuilder = software.amazon.awssdk.services.bedrock.model.ListFoundationModelsRequest.builder();
		
		if (this.ListFoundationModelsRequest.getByCustomizationType() != null) {
			awsRequestBuilder.byCustomizationType(this.ListFoundationModelsRequest.getByCustomizationType().getCaption());
		}
		if (this.ListFoundationModelsRequest.getByInferenceType() != null) {
			awsRequestBuilder.byInferenceType(this.ListFoundationModelsRequest.getByInferenceType().getCaption());
		}
		if (this.ListFoundationModelsRequest.getByOutputModality() != null) {
			awsRequestBuilder.byOutputModality(this.ListFoundationModelsRequest.getByOutputModality().getCaption());
		}
		if (this.ListFoundationModelsRequest.getByProvider() != null && !this.ListFoundationModelsRequest.getByProvider().isBlank()) {
			awsRequestBuilder.byProvider(this.ListFoundationModelsRequest.getByProvider());
		}	
		
		return awsRequestBuilder.build();
		
	}
	
	private ListFoundationModelsResponse getMxResponse(software.amazon.awssdk.services.bedrock.model.ListFoundationModelsResponse awsResponse) {
		
		ListFoundationModelsResponse mxResponse = new ListFoundationModelsResponse(getContext());
		
		List<software.amazon.awssdk.services.bedrock.model.FoundationModelSummary> awsFoundationalModelList = awsResponse.modelSummaries();
		
		for (software.amazon.awssdk.services.bedrock.model.FoundationModelSummary awsFoundationModel : awsFoundationalModelList) {
			FoundationModelSummary mxFoundationalModel = new FoundationModelSummary(getContext());
			mxFoundationalModel.setModelARN(awsFoundationModel.modelArn());
			mxFoundationalModel.setModelID(awsFoundationModel.modelId());
			awsFoundationModel.customizationsSupported().forEach(awsCustomizationsSupported -> createMxSupportedCustomizations(awsCustomizationsSupported,mxFoundationalModel));
			awsFoundationModel.inferenceTypesSupported().forEach(awsInferenceTypesSupported -> createMxSupportedInferenceType(awsInferenceTypesSupported,mxFoundationalModel));
			awsFoundationModel.inputModalities().forEach(awsInputModality -> createMxInputModality(awsInputModality,mxFoundationalModel));
			createMxModelLifecycle(awsFoundationModel.modelLifecycle(),mxFoundationalModel);
			mxFoundationalModel.setModelName(awsFoundationModel.modelName());
			awsFoundationModel.outputModalities().forEach(awsOutputModality -> createMxOutputModality(awsOutputModality,mxFoundationalModel));
			mxFoundationalModel.setProviderName(awsFoundationModel.providerName());
			if (awsFoundationModel.responseStreamingSupported() != null) {
				mxFoundationalModel.setResponseStreamingSupported(awsFoundationModel.responseStreamingSupported());
			} else {
				mxFoundationalModel.setResponseStreamingSupported(false);
			}
			mxFoundationalModel.setFoundationModelSummary_ListFoundationModelsResponse(mxResponse);
		}
		
		return mxResponse;
	}
	
	void createMxSupportedCustomizations(software.amazon.awssdk.services.bedrock.model.ModelCustomization awsCustomizationsSupported, FoundationModelSummary mxFoundationalModel) {
		
		SupportedCustomization mxSupportedCustomizations = new SupportedCustomization(getContext());
		mxSupportedCustomizations.setCustomizationType(ENUM_CustomizationType.valueOf(awsCustomizationsSupported.name()));
		mxSupportedCustomizations.setSupportedCustomization_FoundationModelSummary(mxFoundationalModel);
		
	}
	
	void createMxSupportedInferenceType(software.amazon.awssdk.services.bedrock.model.InferenceType awsInferenceTypesSupported, FoundationModelSummary mxFoundationalModel) {
		
		SupportedInferenceType mxSupportedInferenceType = new SupportedInferenceType(getContext());
		mxSupportedInferenceType.setInferenceType(ENUM_InferenceType.valueOf(awsInferenceTypesSupported.name()));
		mxSupportedInferenceType.setSupportedInferenceType_FoundationModelSummary(mxFoundationalModel);
		
	}
	
	void createMxInputModality(software.amazon.awssdk.services.bedrock.model.ModelModality awsInputModality, FoundationModelSummary mxFoundationalModel) {
		
		InputModality mxInputModality = new InputModality(getContext());
		mxInputModality.setInputModalityType(ENUM_InputOutputModality.valueOf(awsInputModality.name()));
		mxInputModality.setInputModality_FoundationModelSummary(mxFoundationalModel);
		
	}
	
	void createMxOutputModality(software.amazon.awssdk.services.bedrock.model.ModelModality awsOutputModality, FoundationModelSummary mxFoundationalModel) {
		
		OutputModality mxOutputModality = new OutputModality(getContext());
		mxOutputModality.setOutputModalityType(ENUM_InputOutputModality.valueOf(awsOutputModality.name()));
		mxOutputModality.setOutputModality_FoundationModelSummary(mxFoundationalModel);
		
	}
	
	void createMxModelLifecycle(software.amazon.awssdk.services.bedrock.model.FoundationModelLifecycle awsModelLifecycle, FoundationModelSummary mxFoundationalModel) {
		
		FoundationModelLifecycle mxFoundationModelLifecycle = new FoundationModelLifecycle(getContext());
		mxFoundationModelLifecycle.setStatus(ENUM_ModelLifecycleStatus.valueOf(awsModelLifecycle.statusAsString()));
		mxFoundationModelLifecycle.setFoundationModelLifecycle_FoundationModelSummary(mxFoundationalModel);
		
	}

	// END EXTRA CODE
}
