// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.ENUM_KnowledgeBaseStatus;
import amazonbedrockconnector.proxies.KnowledgeBaseSummary;
import amazonbedrockconnector.proxies.ListKnowledgeBasesResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonbedrockconnector.impl.AmazonBedrockClient;

public class ListKnowledgeBases extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region Region;
	private IMendixObject __ListKnowledgeBasesRequest;
	private amazonbedrockconnector.proxies.ListKnowledgeBasesRequest ListKnowledgeBasesRequest;

	public ListKnowledgeBases(IContext context, IMendixObject Credentials, java.lang.String Region, IMendixObject ListKnowledgeBasesRequest)
	{
		super(context);
		this.__Credentials = Credentials;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
		this.__ListKnowledgeBasesRequest = ListKnowledgeBasesRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.ListKnowledgeBasesRequest = this.__ListKnowledgeBasesRequest == null ? null : amazonbedrockconnector.proxies.ListKnowledgeBasesRequest.initialize(getContext(), __ListKnowledgeBasesRequest);

		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(ListKnowledgeBasesRequest, "ListKnowledgeBasesRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			var client = AmazonBedrockClient.getBedrockAgentClient(Credentials, Region, ListKnowledgeBasesRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesRequest awsRequest = getAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesResponse awsResponse = client.listKnowledgeBases(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return getMxResponse(awsResponse).getMendixObject();
			
		} catch (Exception e) {
			
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListKnowledgeBases";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ListKnowledgeBases.class);
	
	software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesRequest getAwsRequest(){
		
		software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesRequest.Builder awsRequestBuilder = software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesRequest.builder();
		
		if (this.ListKnowledgeBasesRequest.getMaxResults()!=null) {
			awsRequestBuilder.maxResults(this.ListKnowledgeBasesRequest.getMaxResults());
		}
		
		if (this.ListKnowledgeBasesRequest.getNextToken() != null && !this.ListKnowledgeBasesRequest.getNextToken().isBlank()) {
			awsRequestBuilder.nextToken(this.ListKnowledgeBasesRequest.getNextToken());
		}
		
		return awsRequestBuilder.build();
	}
	
	ListKnowledgeBasesResponse getMxResponse(software.amazon.awssdk.services.bedrockagent.model.ListKnowledgeBasesResponse awsResponse) {
		
		ListKnowledgeBasesResponse mxResponse = new ListKnowledgeBasesResponse(getContext());
		
		mxResponse.setNextToken(awsResponse.nextToken());
		awsResponse.knowledgeBaseSummaries().forEach(awsSummary -> createMxSummary(awsSummary,mxResponse));
		
		return mxResponse;
	}
	
	void createMxSummary(software.amazon.awssdk.services.bedrockagent.model.KnowledgeBaseSummary awsSummary, ListKnowledgeBasesResponse mxResponse) {
		
		KnowledgeBaseSummary mxSummary = new KnowledgeBaseSummary(getContext());
		mxSummary.setKnowledgeBaseID(awsSummary.knowledgeBaseId());
		mxSummary.setName(awsSummary.name());;
		mxSummary.setStatus(ENUM_KnowledgeBaseStatus.valueOf(awsSummary.statusAsString()));
		mxSummary.setUpdatedAt(Date.from(awsSummary.updatedAt()));
		mxSummary.setDescription(awsSummary.description());
		mxSummary.setKnowledgeBaseSummary_ListKnowledgeBasesResponse(getContext(), mxResponse);
		
	}
	// END EXTRA CODE
}
