// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.AgentSummary;
import amazonbedrockconnector.proxies.ENUM_AgentStatus;
import amazonbedrockconnector.proxies.ListAgentsResponse;
import software.amazon.awssdk.services.bedrockagent.BedrockAgentClient;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonbedrockconnector.impl.AmazonBedrockClient;

public class ListAgents extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region Region;
	private IMendixObject __ListAgentsRequest;
	private amazonbedrockconnector.proxies.ListAgentsRequest ListAgentsRequest;

	public ListAgents(IContext context, IMendixObject Credentials, java.lang.String Region, IMendixObject ListAgentsRequest)
	{
		super(context);
		this.__Credentials = Credentials;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
		this.__ListAgentsRequest = ListAgentsRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.ListAgentsRequest = this.__ListAgentsRequest == null ? null : amazonbedrockconnector.proxies.ListAgentsRequest.initialize(getContext(), __ListAgentsRequest);

		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(ListAgentsRequest, "ListAgentsRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			BedrockAgentClient client = AmazonBedrockClient.getBedrockAgentClient(Credentials, Region, ListAgentsRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.ListAgentsRequest awsRequest = createAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);			
			
			software.amazon.awssdk.services.bedrockagent.model.ListAgentsResponse awsResponse = client.listAgents(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return getMxResponse(awsResponse).getMendixObject();
			
		} catch (Exception e) {
			
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListAgents";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ListAgents.class);
	
	private software.amazon.awssdk.services.bedrockagent.model.ListAgentsRequest createAwsRequest() {
		
		software.amazon.awssdk.services.bedrockagent.model.ListAgentsRequest.Builder awsRequestBuilder = software.amazon.awssdk.services.bedrockagent.model.ListAgentsRequest.builder();
		
		if (this.ListAgentsRequest.getMaxResults()!=null) {
			awsRequestBuilder.maxResults(this.ListAgentsRequest.getMaxResults());
		}
		
		if (this.ListAgentsRequest.getNextToken() != null && !this.ListAgentsRequest.getNextToken().isBlank()) {
			awsRequestBuilder.nextToken(this.ListAgentsRequest.getNextToken());
		}
		
		return awsRequestBuilder.build();
	}
	
	private ListAgentsResponse getMxResponse(software.amazon.awssdk.services.bedrockagent.model.ListAgentsResponse awsResponse) {
		
		ListAgentsResponse mxResponse = new ListAgentsResponse(getContext());
		
		mxResponse.setNextToken(awsResponse.nextToken());
		awsResponse.agentSummaries().forEach(awsAgentSummary -> createMxAgentSummary(awsAgentSummary,mxResponse));
		
		return mxResponse;
	}
	
	void createMxAgentSummary(software.amazon.awssdk.services.bedrockagent.model.AgentSummary awsAgentSummary, ListAgentsResponse mxResponse) {
		
		AgentSummary mxAgentSummary = new AgentSummary(getContext());
		mxAgentSummary.setAgentID(awsAgentSummary.agentId());
		mxAgentSummary.setAgentName(awsAgentSummary.agentName());
		mxAgentSummary.setAgentStatus(ENUM_AgentStatus.valueOf(awsAgentSummary.agentStatusAsString()));
		mxAgentSummary.setDescription(awsAgentSummary.description());
		mxAgentSummary.setLatestAgentVersion(awsAgentSummary.latestAgentVersion());
		mxAgentSummary.setUpdatedAt(Date.from(awsAgentSummary.updatedAt()));
		mxAgentSummary.setAgentSummary_ListAgentsResponse(mxResponse);
	}
	// END EXTRA CODE
}
