// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import java.math.BigDecimal;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxLocation;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.Content;
import amazonbedrockconnector.proxies.RetrievalResult;
import amazonbedrockconnector.proxies.RetrieveLocation;
import amazonbedrockconnector.proxies.RetrieveResponse;
import software.amazon.awssdk.services.bedrockagentruntime.BedrockAgentRuntimeClient;

public class Retrieve extends CustomJavaAction<IMendixObject>
{
	private awsauthentication.proxies.ENUM_Region Region;
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private IMendixObject __RetrieveRequest;
	private amazonbedrockconnector.proxies.RetrieveRequest RetrieveRequest;

	public Retrieve(IContext context, java.lang.String Region, IMendixObject Credentials, IMendixObject RetrieveRequest)
	{
		super(context);
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
		this.__Credentials = Credentials;
		this.__RetrieveRequest = RetrieveRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.RetrieveRequest = this.__RetrieveRequest == null ? null : amazonbedrockconnector.proxies.RetrieveRequest.initialize(getContext(), __RetrieveRequest);

		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required");
			requireNonNull(this.RetrieveRequest, "RetrieveRequest is required");
			requireNonNull(this.Region, "AWS Region is required");
			
			// Validating request body
			validateRequest();
			
			// Mapping and logging of the request body to AWS request object
			var awsRequest = createAwsRequest();
			LOGGER.debug("The following request was sent to AWS: ", awsRequest);
			
			// Client creation, executing request, logging response
			BedrockAgentRuntimeClient bedrockClient = AmazonBedrockClient.getBedrockAgentRuntimeClient(Credentials, Region, RetrieveRequest);
			var awsResponse = bedrockClient.retrieve(awsRequest);
			LOGGER.debug("The following response was received from AWS: ", awsResponse);
			
			// Return the AWS request that's mapped to the MX model
			return createMxResponse(awsResponse).getMendixObject();
		} catch (Exception e) {
			LOGGER.error("Exception occurred: ", e.getMessage());
			throw e;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Retrieve";
	}

	// BEGIN EXTRA CODE
private static final MxLogger LOGGER = new MxLogger(Retrieve.class);
	
	private void validateRequest() throws CoreException { 
		if (this.RetrieveRequest.getKnowledgeBaseId() == null || this.RetrieveRequest.getKnowledgeBaseId().isBlank()) {
			 throw new IllegalArgumentException("The knowledge base ID cannot be empty or blank.");
		}
		
		if (this.RetrieveRequest.getQueryText() == null || this.RetrieveRequest.getQueryText().isBlank()) {
			throw new IllegalArgumentException("The retrieval query text cannot be empty or blank.");
		}
	}
	
	private software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveRequest createAwsRequest() throws CoreException {
		var awsRequestBuilder = software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveRequest.builder()
				.knowledgeBaseId(this.RetrieveRequest.getKnowledgeBaseId())
				.nextToken(this.RetrieveRequest.getNextToken())
				.retrievalQuery(createRetrievalQuery());
		
		if (RetrieveRequest.getRetrieveRequest_RetrievalConfiguration() != null && RetrieveRequest.getRetrieveRequest_RetrievalConfiguration().getNumberOfResults() != null) {
			awsRequestBuilder.retrievalConfiguration(createAwsRetrievalConfiguration());
		}
		
		return awsRequestBuilder.build();
	}
	
	private software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseQuery createRetrievalQuery() throws CoreException {
		var awsRetrievalQuery = software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseQuery.builder()
				.text(this.RetrieveRequest.getQueryText())
				.build();
		return awsRetrievalQuery;
	}
	
	private software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseRetrievalConfiguration createAwsRetrievalConfiguration() throws CoreException {
		var awsKnowledgeBaseVectorSearchConfiguration = software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseVectorSearchConfiguration.builder()
				.numberOfResults(this.RetrieveRequest.getRetrieveRequest_RetrievalConfiguration().getNumberOfResults())
				.build();
		
		var awsRetrievalConfiguration = software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseRetrievalConfiguration.builder()
				.vectorSearchConfiguration(awsKnowledgeBaseVectorSearchConfiguration)
				.build();
		
		return awsRetrievalConfiguration;
	}
	
	private RetrieveResponse createMxResponse(software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveResponse awsResponse) {
		RetrieveResponse mxResponse = new RetrieveResponse(getContext());
		mxResponse.setNextToken(awsResponse.nextToken());
		
		if (!awsResponse.retrievalResults().isEmpty()) {
			awsResponse.retrievalResults().forEach(awsRetrievalResult -> createMxRetrievalResult(awsRetrievalResult,mxResponse));
		}
		
		return mxResponse;
	}
	
	private void createMxRetrievalResult(software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseRetrievalResult awsRetrievalResult, RetrieveResponse mxResponse) {
		RetrievalResult mxRetrievalResult = new RetrievalResult(getContext());
		mxRetrievalResult.setScore(BigDecimal.valueOf(awsRetrievalResult.score()));
		mxRetrievalResult.setRetrievalResult_RetrieveResponse(mxResponse);
		
		Content mxContent = createMxContent(awsRetrievalResult.content());
		mxContent.setRetrievalResult_Content(mxRetrievalResult);
		
		RetrieveLocation mxLocation = new RetrieveLocation(getContext());
		MxLocation.setMxLocation(mxLocation, awsRetrievalResult.location(), getContext());
		mxLocation.setRetrievalResult_RetrieveLocation(mxRetrievalResult);
	}
	
	private Content createMxContent(software.amazon.awssdk.services.bedrockagentruntime.model.RetrievalResultContent awsContent) {
		Content mxContent = new Content(getContext());
		mxContent.setText(awsContent.text());
		return mxContent;
	}
	
	
	// END EXTRA CODE
}
