// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonbedrockconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxIngestionJob;
import amazonbedrockconnector.impl.MxLogger;
import software.amazon.awssdk.services.bedrockagent.BedrockAgentClient;
import software.amazon.awssdk.services.bedrockagent.model.StartIngestionJobRequest;

public class StartIngestionJob extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region ENUM_Region;
	private IMendixObject __StartIngestionJobRequest;
	private amazonbedrockconnector.proxies.StartIngestionJobRequest StartIngestionJobRequest;

	public StartIngestionJob(IContext context, IMendixObject Credentials, java.lang.String ENUM_Region, IMendixObject StartIngestionJobRequest)
	{
		super(context);
		this.__Credentials = Credentials;
		this.ENUM_Region = ENUM_Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(ENUM_Region);
		this.__StartIngestionJobRequest = StartIngestionJobRequest;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.StartIngestionJobRequest = this.__StartIngestionJobRequest == null ? null : amazonbedrockconnector.proxies.StartIngestionJobRequest.initialize(getContext(), __StartIngestionJobRequest);

		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(StartIngestionJobRequest, "StartIngestionJobRequest is required");
			requireNonNull(ENUM_Region, "AWS Region is required");
			
			validateRequest();

			BedrockAgentClient BRclient = AmazonBedrockClient.getBedrockAgentClient(Credentials, ENUM_Region, StartIngestionJobRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.StartIngestionJobRequest awsRequest = getAwsRequest();
			LOGGER.info("AWS request: " + awsRequest);
			
			software.amazon.awssdk.services.bedrockagent.model.StartIngestionJobResponse awsResponse = BRclient.startIngestionJob(awsRequest);
			LOGGER.info("AWS response: " + awsResponse);
			
			return MxIngestionJob.getMxResponse(awsResponse, getContext()).getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartIngestionJob";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(StartIngestionJob.class);
	
	private void validateRequest() {
		if (StartIngestionJobRequest.getDataSourceId() == null || StartIngestionJobRequest.getDataSourceId().isBlank()) {
			throw new IllegalArgumentException("DataSourceId is required. Please provide the data source id of the model you want to invoke.");
		}
		
		if (StartIngestionJobRequest.getKnowledgeBaseId() == null || StartIngestionJobRequest.getKnowledgeBaseId().isBlank()) {
			throw new IllegalArgumentException("KnowledgeBaseId is required. Please provide the knowledge base id of the knowledge base you want to invoke.");
		}
	}

	private StartIngestionJobRequest getAwsRequest() {
		return software.amazon.awssdk.services.bedrockagent.model.StartIngestionJobRequest.builder()
		.dataSourceId(StartIngestionJobRequest.getDataSourceId())
		.knowledgeBaseId(StartIngestionJobRequest.getKnowledgeBaseId())
		.description(StartIngestionJobRequest.getDescription())
		.clientToken(StartIngestionJobRequest.getClientToken())
		.build();
	}
	// END EXTRA CODE
}
