// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.CreateBucketResponse;
import awsauthentication.proxies.ENUM_Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.BucketLocationConstraint;
import software.amazon.awssdk.services.s3.model.CreateBucketRequest.Builder;

public class CreateBucket extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __CreateBucketRequest;
	private amazons3connector.proxies.CreateBucketRequest CreateBucketRequest;
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private awsauthentication.proxies.ENUM_Region Region;

	public CreateBucket(IContext context, IMendixObject CreateBucketRequest, IMendixObject Credentials, java.lang.String Region)
	{
		super(context);
		this.__CreateBucketRequest = CreateBucketRequest;
		this.__Credentials = Credentials;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.CreateBucketRequest = this.__CreateBucketRequest == null ? null : amazons3connector.proxies.CreateBucketRequest.initialize(getContext(), __CreateBucketRequest);

		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		// BEGIN USER CODE
		software.amazon.awssdk.services.s3.model.CreateBucketResponse awsResponse = null;
		try {
			// Validation of input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.Region, "AWS Region is required.");
			requireNonNull(this.CreateBucketRequest, "CreateBucketRequest is required.");
			// Validation of the CreateBucketRequest object
			validateRequest();
			// Building the Java CreateBucketRequest
			Builder awsRequestBuilder = software.amazon.awssdk.services.s3.model.CreateBucketRequest.builder()
				.bucket(CreateBucketRequest.getBucketName());
			// Setting of the CreateBucketConfiguration parameter
			// Skipping when US_East_1 is selected, because it is the default region. If empty, the region of the endpoint (input parameter of operation) is used. 
			ENUM_Region locationConstraint = CreateBucketRequest.getLocationConstraint() != null ? CreateBucketRequest.getLocationConstraint() : ENUM_Region.us_east_1;
			if (!locationConstraint.equals(ENUM_Region.us_east_1)) {
				awsRequestBuilder.createBucketConfiguration(createAwsCreateBucketConfiguration(locationConstraint));
			}
			// Finalizing and logging of the request building
			software.amazon.awssdk.services.s3.model.CreateBucketRequest awsRequest = awsRequestBuilder.build();
			LOGGER.debug("AWS request:", awsRequest);
			// Client creation
			S3Client client = AmazonS3Client.getS3Client(Credentials, Region, CreateBucketRequest);
			awsResponse = client.createBucket(awsRequest);
			LOGGER.debug("AWS response:", awsResponse);
		}
		catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}		

		return createMxResponse(awsResponse).getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateBucket";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(CreateBucket.class);
	
	private void validateRequest() throws CoreException {	
		// Validate name
		requireNonNull(CreateBucketRequest.getBucketName(), "Bucket name is required");
		if (CreateBucketRequest.getBucketName().isBlank()) {
			throw new IllegalArgumentException("Bucket name cannot be empty or blank");
		}
		
		// If a different LocationConstraint than Credentials Region is used, the Region must be US-East-1.
		// This is the only Region where bucket creation in a different region is works, because US-East-1 uses the global endpoint (s3.amazonaws.com) that allows that.
		// Other regions use region-specific endpoints (s3.region.amazonaws.com) that allow only for a bucket to be created in that specific region.
		if (CreateBucketRequest.getLocationConstraint() != null) {
			if (!Region.equals(ENUM_Region.us_east_1) && !CreateBucketRequest.getLocationConstraint().equals(Region) ) {
				throw new IllegalArgumentException("Specifying a LocationConstraint to create a bucket in a different region is currently only supported when using 'US-East-1' as the region of the CreateBucket operation.");		}
		}
		
	}
	
	private software.amazon.awssdk.services.s3.model.CreateBucketConfiguration createAwsCreateBucketConfiguration (ENUM_Region region) {
		return software.amazon.awssdk.services.s3.model.CreateBucketConfiguration.builder()
				.locationConstraint(getAwsBucketLocationConstraintFromThisRegion(region))
				.build();
	}
	
	private BucketLocationConstraint getAwsBucketLocationConstraintFromThisRegion (ENUM_Region mxRegionEnumeration) {
		
		try {
			return BucketLocationConstraint.valueOf(mxRegionEnumeration.toString().toUpperCase());
		}
		catch(IllegalArgumentException e) {
			LOGGER.error("The selected region is not supported for a create bucket location constraint. Updating the aws jar libraries may resolve this issue.");
			throw new MendixRuntimeException("The selected region is not supported for a create bucket location constraint. Updating the aws jar libraries may resolve this issue.");
		}
		
	}
	
	private CreateBucketResponse createMxResponse(software.amazon.awssdk.services.s3.model.CreateBucketResponse awsResponse) {
		CreateBucketResponse mxResponse = new CreateBucketResponse(getContext());
		mxResponse.setLocation(awsResponse.location());
		return mxResponse;
	}
	
	// END EXTRA CODE
}
