// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.DeleteObjectRequest.Builder;

public class DeleteObject extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __Credentials;
	private awsauthentication.proxies.Credentials Credentials;
	private IMendixObject __DeleteObjectRequest;
	private amazons3connector.proxies.DeleteObjectRequest DeleteObjectRequest;
	private awsauthentication.proxies.ENUM_Region Region;

	public DeleteObject(IContext context, IMendixObject Credentials, IMendixObject DeleteObjectRequest, java.lang.String Region)
	{
		super(context);
		this.__Credentials = Credentials;
		this.__DeleteObjectRequest = DeleteObjectRequest;
		this.Region = Region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(Region);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Credentials = this.__Credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), __Credentials);

		this.DeleteObjectRequest = this.__DeleteObjectRequest == null ? null : amazons3connector.proxies.DeleteObjectRequest.initialize(getContext(), __DeleteObjectRequest);

		// BEGIN USER CODE
			software.amazon.awssdk.services.s3.model.DeleteObjectResponse awsResponse = null;	
			try {
				// Validation of input parameters
				requireNonNull(this.Credentials, "AWS Credentials are required.");
				requireNonNull(this.DeleteObjectRequest, "DeleteObjectRequest is required.");
				requireNonNull(this.Region, "AWS Region is required.");
				
				// Validation of the DeleteObjectRequest object
				validateRequest();
				
				// Building the AWS DeleteObjectRequest
				software.amazon.awssdk.services.s3.model.DeleteObjectRequest awsRequest = createAWSRequest();
				
				// Logging of the request building
				LOGGER.debug("AWS request:", awsRequest);
				
				// Client creation
				S3Client client = AmazonS3Client.getS3Client(Credentials, Region, DeleteObjectRequest);
				
				// Invoke action on AWS client
				awsResponse = client.deleteObject(awsRequest);
				
				// Log the response
				LOGGER.debug("AWS response:", awsResponse);
			}
			catch (Exception e) {
				LOGGER.error(e.getMessage());
				throw e;
				}
			
			return awsResponse.sdkHttpResponse().isSuccessful();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteObject";
	}

	// BEGIN EXTRA CODE
		private static final MxLogger LOGGER = new MxLogger(DeleteObject.class);
		
		private void validateRequest() throws CoreException {	
	
			// Validate key 
			requireNonNull(DeleteObjectRequest.getKey(), "Key is required");
			if (DeleteObjectRequest.getKey().isBlank()) {
			throw new IllegalArgumentException("Key cannot be blank");
			}
			
			// Validate bucket name 
			requireNonNull(DeleteObjectRequest.getBucketName(), "Bucket name is required");
			if (DeleteObjectRequest.getBucketName().isBlank()) {
				throw new IllegalArgumentException("Bucket name cannot be blank");
			}
			
		}
		
		private software.amazon.awssdk.services.s3.model.DeleteObjectRequest createAWSRequest() {
			Builder awsRequestBuilder = software.amazon.awssdk.services.s3.model.DeleteObjectRequest.builder()
				.bucket(DeleteObjectRequest.getBucketName())
				.key(DeleteObjectRequest.getKey());
			return awsRequestBuilder.build();
		}
	// END EXTRA CODE
}
