// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} elementClassToIdentify
 * @param {boolean} submitOnEnter
 * @param {boolean} submitOnShiftEnter
 * @param {Nanoflow} nanoflowToExecute
 * @param {MxObject} chatContext
 * @returns {Promise.<void>}
 */
export async function Textarea_HitEnter(elementClassToIdentify, submitOnEnter, submitOnShiftEnter, nanoflowToExecute, chatContext) {
	// BEGIN USER CODE
	try{
		//need to get the element by "classname" because "ID" does not exist for mendix elements and "tag name" changes dynamically
		document.getElementsByClassName(elementClassToIdentify)[0].addEventListener('keydown', function(event) {
			console.log("added event listener");
    		if (event.key === 'Enter') {
      			if (event.shiftKey) {
        			if (submitOnShiftEnter) {
						nanoflowToExecute({ChatContext: chatContext}); 				
        			}
      			} else if (!event.ctrlKey && !event.altKey && !event.metaKey) {
        			if (submitOnEnter) {
						nanoflowToExecute({ChatContext: chatContext});
        			}
      			}
    		}
  		});
	}
	catch(err) {
		console.log(err)
	} 

	// END USER CODE
}
