// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} textAreaName
 * @param {string} buttonName
 * @param {boolean} submitOnEnter
 * @param {boolean} submitOnShiftEnter
 * @returns {Promise.<void>}
 */
export async function Textarea_HitEnter(textAreaName, buttonName, submitOnEnter, submitOnShiftEnter) {
	// BEGIN USER CODE
	try{
		//Validations
		if (!textAreaName || textAreaName.trim().length === 0){
			throw new Error("textAreaName is required.")
		}
		if (!buttonName || buttonName.trim().length === 0){
			throw new Error("buttonName is required.")
		}

		//Get textAreaElement. The mx-name is part of the ID.
		var textAreaElement = document.querySelector('textarea[id*="' + textAreaName + '"]');
		if (textAreaElement === null){
				throw new Error("Textarea with that name could not be found.")
		}

		//Add Event Listener that clicks the button
		textAreaElement.addEventListener('keydown', function(event) {
			//Get buttonElement. The mx-name is part of the class name
			var buttonElement = document.querySelector('button[class*="' + buttonName + '"]');
			if (buttonElement === null){
				throw new Error("Button with that name could not be found.")
			}

    		if (event.key === 'Enter') {
      			if (event.shiftKey) {
        			if (submitOnShiftEnter) {
						buttonElement.click();			
        			}
      			} else if (!event.ctrlKey && !event.altKey && !event.metaKey) {
        			if (submitOnEnter) {
						buttonElement.click();
        			}
      			}
    		}
  		});
	}
	catch(err) {
		console.error(err)
	} 

	// END USER CODE
}
