// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import openaiconnector.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ChatCompletionsRequest_TransformExportMapping extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __ChatCompletionsRequest;
	private openaiconnector.proxies.ChatCompletionsRequest ChatCompletionsRequest;
	private java.lang.String ChatCompletionsRequest_Json;

	public ChatCompletionsRequest_TransformExportMapping(IContext context, IMendixObject ChatCompletionsRequest, java.lang.String ChatCompletionsRequest_Json)
	{
		super(context);
		this.__ChatCompletionsRequest = ChatCompletionsRequest;
		this.ChatCompletionsRequest_Json = ChatCompletionsRequest_Json;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.ChatCompletionsRequest = this.__ChatCompletionsRequest == null ? null : openaiconnector.proxies.ChatCompletionsRequest.initialize(getContext(), __ChatCompletionsRequest);

		// BEGIN USER CODE
		try {
			requireNonNull(ChatCompletionsRequest, "ChatCompletionsRequest is required.");
			return ChatCompletionsRequest_Json.replace(",\"tool_calls\":[]", "");
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ChatCompletionsRequest_TransformExportMapping";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ChatCompletionsRequest_TransformExportMapping.class);
	// END EXTRA CODE
}
