// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import openaiconnector.impl.MxLogger;

public class EmbeddingsResponse_PrepareForImportMapping extends CustomJavaAction<java.lang.String>
{
	private java.lang.String EmbeddingsResponse;

	public EmbeddingsResponse_PrepareForImportMapping(IContext context, java.lang.String EmbeddingsResponse)
	{
		super(context);
		this.EmbeddingsResponse = EmbeddingsResponse;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(EmbeddingsResponse, "EmbeddingsResponse is required.");
			
			rootNode = MAPPER.readTree(EmbeddingsResponse);
			updateEmbeddingVector();
			
			return MAPPER.writeValueAsString(rootNode);
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EmbeddingsResponse_PrepareForImportMapping";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(EmbeddingsResponse_PrepareForImportMapping.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();
	private JsonNode rootNode;
	
	private void updateEmbeddingVector() throws JsonProcessingException {
		JsonNode dataArray = rootNode.path("data");
		for(JsonNode data : dataArray) {
			JsonNode embedding = data.path("embedding");
			String embeddingString = (embedding != null ? MAPPER.writeValueAsString(embedding) : null);
			((ObjectNode) data).put("embedding", embeddingString);
		}
		((ObjectNode) rootNode).set("data", dataArray);
	}
	// END EXTRA CODE
}
