// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import openaiconnector.impl.MxLogger;
import openaiconnector.impl.FunctionCollectionImpl;
import openaiconnector.impl.FunctionImpl;
import openaiconnector.proxies.ENUM_ToolChoice;
import openaiconnector.proxies.Function;

public class FunctionCollection_AddFunction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __FunctionCollection;
	private openaiconnector.proxies.FunctionCollection FunctionCollection;
	private java.lang.String FunctionName;
	private java.lang.String FunctionMicroflow;
	private java.lang.String FunctionDescription;
	private java.lang.Boolean IsFunctionToolChoice;

	public FunctionCollection_AddFunction(IContext context, IMendixObject FunctionCollection, java.lang.String FunctionName, java.lang.String FunctionMicroflow, java.lang.String FunctionDescription, java.lang.Boolean IsFunctionToolChoice)
	{
		super(context);
		this.__FunctionCollection = FunctionCollection;
		this.FunctionName = FunctionName;
		this.FunctionMicroflow = FunctionMicroflow;
		this.FunctionDescription = FunctionDescription;
		this.IsFunctionToolChoice = IsFunctionToolChoice;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.FunctionCollection = this.__FunctionCollection == null ? null : openaiconnector.proxies.FunctionCollection.initialize(getContext(), __FunctionCollection);

		// BEGIN USER CODE
		try{
			requireNonNull(FunctionCollection, "FunctionCollection object is required.");
			FunctionImpl.validateInput(FunctionMicroflow, FunctionName);
			
			Function function = FunctionImpl.createFunction(getContext(), FunctionMicroflow, FunctionName, FunctionDescription, FunctionCollection);
			
			if(IsFunctionToolChoice) {
				FunctionCollectionImpl.setToolChoice(FunctionCollection, ENUM_ToolChoice.function, function);
			}
			
			return null;
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FunctionCollection_AddFunction";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(FunctionCollection_AddFunction.class);
	// END EXTRA CODE
}
