// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import openaiconnector.impl.MxLogger;
import openaiconnector.impl.FunctionImpl;
import openaiconnector.proxies.Function;

public class Function_Create extends CustomJavaAction<IMendixObject>
{
	private java.lang.String Name;
	private java.lang.String FunctionMicroflow;
	private IMendixObject __FunctionCalling;
	private openaiconnector.proxies.FunctionCollection FunctionCalling;
	private java.lang.String Description;

	public Function_Create(IContext context, java.lang.String Name, java.lang.String FunctionMicroflow, IMendixObject FunctionCalling, java.lang.String Description)
	{
		super(context);
		this.Name = Name;
		this.FunctionMicroflow = FunctionMicroflow;
		this.__FunctionCalling = FunctionCalling;
		this.Description = Description;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.FunctionCalling = this.__FunctionCalling == null ? null : openaiconnector.proxies.FunctionCollection.initialize(getContext(), __FunctionCalling);

		// BEGIN USER CODE
		try{
			requireNonNull(FunctionCalling, "FunctionCalling object is required.");
			FunctionImpl.validateInput(FunctionMicroflow, Name);
			
			Function function = new Function(getContext());
			function.setFunctionMicroflow(FunctionMicroflow);
			function.setName(Name);	
			function.setDescription(Description); //Optional parameter
			function.setFunction_FunctionCollection(FunctionCalling);
			
			return function.getMendixObject();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Function_Create";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Function_Create.class);
	// END EXTRA CODE
}
