// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.MxLogger;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Function_ExecuteFunctionMicroflow extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Function;
	private genaicommons.proxies.Function Function;
	private java.lang.String Arguments;

	public Function_ExecuteFunctionMicroflow(IContext context, IMendixObject Function, java.lang.String Arguments)
	{
		super(context);
		this.__Function = Function;
		this.Arguments = Arguments;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Function = this.__Function == null ? null : genaicommons.proxies.Function.initialize(getContext(), __Function);

		// BEGIN USER CODE
		try {
			requireNonNull(Function, "Function is required.");
			requireNonNull(Function.getMicroflow(), "Function has no FunctionMicroflow.");
			
			return executeFunctionMicroflow();
		
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Function_ExecuteFunctionMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Function_ExecuteFunctionMicroflow.class);
	private static ObjectMapper mapper = new ObjectMapper();
	private JsonNode rootNodeArguments;
	
	private String executeFunctionMicroflow() throws Exception {
		String firstInputParamName = FunctionImpl.getFirstInputParamName(Function.getMicroflow());
		
		if(firstInputParamName == null || firstInputParamName.isBlank()){
			return executeAndLogFunctionMicroflow(null, null);
		
		} else {
			rootNodeArguments = mapper.readTree(Arguments);
			JsonNode firstInputParamNode = rootNodeArguments.path(firstInputParamName);
			
			if (!firstInputParamNode.isTextual()) {
				throw new IllegalArgumentException("Arguments " + Arguments + " does not match the expected input of the function microflow " + Function.getMicroflow()+ ".");		
			}
			return executeAndLogFunctionMicroflow(firstInputParamName, firstInputParamNode.asText());
		}
	}
	
	private String executeAndLogFunctionMicroflow(String firstInputParamName, String firstInputParamValue) {
		String response;
		String logMessageInfo = "Finished calling microflow " + Function.getMicroflow() + " with " + getContext();
		String logMessageTrace = logMessageInfo;
		long startTime = System.currentTimeMillis();
		if(firstInputParamName == null || firstInputParamName.isBlank()) {
			logMessageTrace = logMessageTrace + "\nwithout input parameters ";
			response = Core.microflowCall(Function.getMicroflow()).execute(getContext());
		} else {
			logMessageTrace = logMessageTrace +  "\n\nInput parameter [" + firstInputParamName + "]:\n" + firstInputParamValue;
			response = Core.microflowCall(Function.getMicroflow()).withParam(firstInputParamName, firstInputParamValue).execute(getContext());
		}
		long endTime = System.currentTimeMillis();
		long executionTime = endTime - startTime;
		String duration = "\n\nDuration:\n" + executionTime + "ms";
		LOGGER.info(logMessageInfo + duration);
		LOGGER.trace(logMessageTrace+ "\n\nReturn value:\n" + response + duration);
		return response;
	}
	
	// END EXTRA CODE
}
