// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Response_GetResponseImageList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String ResponseImageType;
	private IMendixObject __Response;
	private genaicommons.proxies.Response Response;

	public Response_GetResponseImageList(IContext context, java.lang.String ResponseImageType, IMendixObject Response)
	{
		super(context);
		this.ResponseImageType = ResponseImageType;
		this.__Response = Response;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.Response = this.__Response == null ? null : genaicommons.proxies.Response.initialize(getContext(), __Response);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Response_GetResponseImageList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
