// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;

import java.util.ArrayList;
import java.util.List;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

import genaicommons.impl.FileContentImpl;
import genaicommons.impl.ImageGenImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.FileContent;

public class Response_GetResponseImageList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String ResponseImageType;
	private IMendixObject __Response;
	private genaicommons.proxies.Response Response;

	public Response_GetResponseImageList(IContext context, java.lang.String ResponseImageType, IMendixObject Response)
	{
		super(context);
		this.ResponseImageType = ResponseImageType;
		this.__Response = Response;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.Response = this.__Response == null ? null : genaicommons.proxies.Response.initialize(getContext(), __Response);

		// BEGIN USER CODE
		try {
			requireNonNull(Response, "Response is required.");
			requireNonNull(ResponseImageType, "ResponseImageEntity is required");
			
			List<FileContent> fileContentList = FileContentImpl.getFileContentList(Response);
			List<IMendixObject> returnList = createGeneratedImageList(fileContentList);
			
			return returnList;
			
		} catch (Exception e) {
			LOGGER.error("An error ocurred while creating the response image list: " + e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Response_GetResponseImageList";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Response_GetResponseImageList.class);
	
	private List<IMendixObject> createGeneratedImageList(List<FileContent> fileContentList) {
		List<IMendixObject> imageList = new ArrayList<>();
		
		for (FileContent fileContent : fileContentList) {
			if (fileContent == null || fileContent.getFileContent().isBlank()) {
				LOGGER.warn("Empty FileContent found as part of the response.");
				continue;
			}
			IMendixObject generatedImage = ImageGenImpl.createGeneratedImage(ResponseImageType, getContext());
			ImageGenImpl.decodeToFile(generatedImage, fileContent, getContext());
			imageList.add(generatedImage);
		}
		
		return imageList;
	}
	
	// END EXTRA CODE
}
